'''
    pdfRotate.py

    This script rotates the output PDF file generated by
    pdfFusion by 90deg CW.

    Jose Antonio Klautau Toffoli 
    2023-09-09
'''

# Import libraries.
import PyPDF2 as pdf

# Open the file to be rotated.
pdf_file = open('merged_file.pdf', 'rb')

# Initialize reader and writer objects.
reader = pdf.PdfReader(pdf_file)
writer = pdf.PdfWriter()

# Iterate through each page in pdf file and rotate by 90deg CW.
for page in reader.pages:
    page.rotate(90)
    writer.add_page(page)

# Save rotated file version.
pdf_out = open('merged_file.pdf', 'wb')
writer.write(pdf_out)

# Finalize all objects.
pdf_out.close()
pdf_file.close()
writer.close()